sudo: false
language: go
go:
  - 1.7.1
  - tip
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
install:
  - go get github.com/mattn/goveralls
script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go tool vet .
  - go test -v -race ./...
  - go test -covermode=count -coverprofile=profile.cov ./asana
after_success:
  - goveralls -coverprofile=profile.cov -service=travis-ci
