language: go

go:
 - tip

install:
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/google/go-querystring/query

before_script:
  - export PATH=$HOME/gopath/bin:$PATH

script:
  - go test -covermode=count -coverprofile=profile.cov ./asana

after_success:
  - goveralls -coverprofile=profile.cov -service=travis-ci
